In [69]:
import random
import numpy as np
import matplotlib.pyplot as plt

X= np.random.randn(3,6) 
W = np.random.randn(6, 3)
y = np.array(range(0,3))
#print(y.shape)
dW = np.zeros(W.shape) # initialize the gradient as zero
num_train = X.shape[0]

  #############################################################################
  # Implement a vectorized version of the structured SVM loss, storing the    #
  # result in loss.                                                           #
  #############################################################################
scores = X.dot(W)
#print(scores.shape)
#print(scores)
yi_scores = scores[np.arange(scores.shape[0]),y] # http://stackoverflow.com/a/23435843/459241 
#print(yi_scores)
#print(scores - np.matrix(yi_scores).T +1)
margins = np.maximum(0, scores - np.matrix(yi_scores).T + 1)
margins[np.arange(num_train),y] = 0
#print(margins)
binary = margins
binary[margins > 0] = 1
print(binary)
row_sum = np.sum(binary, axis=1)
print(row_sum)
binary[np.arange(num_train), y] = -row_sum.T
print(binary)

[[0. 1. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]
[[1.]
 [0.]
 [2.]]
[[-1.  1.  0.]
 [ 0. -0.  0.]
 [ 1.  1. -2.]]
